createCodeTable2(codeRODS,
		[
			{ name: "Cs_cd"},
			{ name: "Cs_name"},
			{ name: "Address"},
			{ name: "Country"},
			{ name: "City"},
			{ name: "Fax"},
			{ name: "Phone"},
			{ name: "Email"},
			{ name: "Note"},
			{ name: "Updated"},
			{ name: "Del_mark"},
			{ name: "grading"},
			{ name: "hide"},
			{ name: "web_address"},
			{ name: "iacs_cd"},

		],
		[
			{ name: "Cs_cd", required:true },
			{ name: "Cs_name"},
			{ name: "Address"},
			{ name: "Country"},
			{ name: "City"},
			{ name: "Fax"},
			{ name: "Phone"},
			{ name: "Email"},
			{ name: "Note"},
			{ name: "Updated"},
			{ name: "Del_mark"},
			{ name: "grading"},
			{ name: "hide"},
			{ name: "web_address"},
			{ name: "iacs_cd"},

		],
		["Cs_cd"], 'paged', 'CODE_RO_WRITE|CODETABLE_ALL');