create_query_export_form(shipManagementDS,
	[
		{ name: "id", 				width:120},
		{ name: "spname", 			width:100},
		{ name: "imono",			width:100},
		{ name: "distinct_no", 		width:120},
		{ name: "offno",			width:140},
		{ name: "sptype",			width:120},
		{ name: "gross", 			width:120},
		{ name: "engine_power", 	width:120},
		{ name: "trading_area", 	width:120},
		{ name: "registry_port", 	width:120},
		{ name: "dw", 				width:120},
		{ name: "net", 				width:120},
		{ name: "pp", 				width:120},
		{ name: "loa", 				width:120},
		{ name: "breadth", 			width:120},
		{ name: "depth", 			width:120},
		{ name: "speed", 			width:120},
		{ name: "register_date", 	width:120},
		{ name: "class", 			width:120},
		{ name: "stat", 			width:120},
		{ name: "flag", 			width:120},
		{ name: "operator", 		width:120},
	],
	[
		{ name: "spname", title: "Name of Ship", type: "text"},
		{ name: "imono", title: "IMO NO.", type: "text"},
		{ name: "distinct_no", title: "Distinct No.", type: "text"},
		{ name: "sptype", title: "Type of Ship", type: "text"},
		{ name: "offno", title: "Off. No.", type: "text"},
		{ name: "gross", title: "Gross", type: "text"},
		{ name: "gross", title: "Gross", type: "text"},
	],
	[], ["id"], 'paged');

// create_query_export_form(shipManagementDS, [], [], ["id"], 'paged');
