createCodeTable2(companyRPDS,
		[
			{ name: "Com_cd", width: 100},
			{ name: "Com_name", width: 150},
			{ name: "Address1", width: 160},
			{ name: "Address2", width: 160},
			{ name: "Address3", width: 160},
			{ name: "Address4", width: 160},
			{ name: "Fax", width: 100},
			{ name: "Phone", width: 100},
			{ name: "Email", width: 100},
			{ name: "Person", width: 100},
			{ name: "rpCR", width: 160},
//			{ name: "Remark", width: 100},
//			{ name: "Updated", width: 100},
//			{ name: "Del_mark"},
//			{ name: "ansback", width: 100},
		],
		[
//			{ name: "Com_cd", required: true},
			{ name: "Com_cd", disabled: true, canEdit:false},	//test
			{ name: "Com_name", required: true},
			{ name: "Address1"},
			{ name: "Address2"},
			{ name: "Address3"},
			{ name: "Address4"},
			{ name: "Fax"},
			{ name: "Phone"},
			{ name: "Email"},
			{ name: "Person"},
			{ name: "rpCR"},
//			{ name: "Remark"},
//			{ name: "Updated"},
//			{ name: "Del_mark"},
//			{ name: "ansback"}
		],
		["Com_cd"], 'paged','CODE_REP_PER_WRITE|CODETABLE_ALL');